### ISSUE TITLE
ckpt name seems not match

### ISSUE THREAD

**Issue by howardgriffin** [drboog/Shifted_Diffusion#2]
![IMG_2192](https://user-images.githubusercontent.com/23454942/231124857-9f595ae1-12bb-4e76-aff3-36cfb75dbffa.jpeg)

**Comment by drboog** [comment]
Could you provide the library versions you are using (such as transformers, x_transformers) ?

**Comment by howardgriffin** [comment]
> Could you provide the library versions you are using (such as transformers, x_transformers) ?

Here is my 'transformers' and 'x-transformers' library version of my environment:
transformers                4.26.0
x-transformers              1.10.0

**Comment by drboog** [comment]
I guess maybe there is some library mismatching problem. As a result, the parameters in our checkpoint have different names with parameters of model you initialized (with another version of library).

I think you can print the name of parameters from checkpoint and model you initialized, compare them and manually change the names, then load the parameters.

Or you can install the version provided in our requirements.txt (create a new environment so that it won't influence your other projects).

**Comment by howardgriffin** [comment]
Thank you for your reply, I will have a try.

> I guess maybe there is some library mismatching problem. As a result, the parameters in our checkpoint have different names with parameters of model you initialized (with another version of library).
> 
> I think you can print the name of parameters from checkpoint and model you initialized, compare them and manually change the names, then load the parameters.
> 
> Or you can install the version provided in our requirements.txt (create a new environment so that it won't influence your other projects).

**Comment by howardgriffin** [comment]
I change the the version of 'x_transformers' following your requiremets, everything goes ok.

**Comment by rutuja1409** [comment]
> I change the the version of 'x_transformers' following your requirements, everything goes ok.

Hey @howardgriffin I am having similar issue, can you please help me out. I have trained the model on my custom dataset and stored the checkpoint. Below is the screenshot how stored checkpoint looks like
![image](https://github.com/user-attachments/assets/bdbf5eee-4e82-4a96-914f-5863cb927959)

Now, while running sft_test.py what path have you provided for prior and model path?Can you help me out? Beacuse the prior path expects a .th file while in checkpoint I have prior.pt file. 
![image](https://github.com/user-attachments/assets/fab114db-fe17-401c-a6d1-ab4c9e976cbb)

Thank you!!
