### ISSUE TITLE
About ckpt

### ISSUE THREAD

**Issue by victorup** [drboog/Shifted_Diffusion#3]
Hi, thanks for your work!

I encountered a problem when I run ‘sft_test.py’: 

`Some weights of the model checkpoint at t5-11b were not used when initializing T5EncoderModel: ['
decoder.block.17.layer.1.EncDecAttention.v.weight', 'decoder.block.12.layer.0.layer_norm.weight',
 'decoder.block.17.layer.0.SelfAttention.v.weight', 'decoder.block.5.layer.0.layer_norm.weight', 
'decoder.block.0.layer.0.SelfAttention.relative_attention_bias.weight', 'decoder.block.14.layer.1
.EncDecAttention.o.weight', 'decoder.block.13.layer.0.SelfAttention.v.weight', 'decoder.block.18.
layer.1.EncDecAttention.k.weight', ...`

Is this normal？

And it will be out of memory.

Then I tried to switch to "t5-large" model. However, the generated images are not corresponding with input text. 

For example: text = 'a yellow and blue train riding a track by some trees'
![prior_a yellow and blue train riding a track by some trees](https://user-images.githubusercontent.com/44796817/231814211-0f7eb0df-822f-4898-adc1-e9c68424e6dd.jpg)

**Comment by drboog** [comment]
I guess some weights are not loaded because of out of memory.

If you use t5-large, then it will not generate meaningful images, because of our model is trained on t5-11b representations

If running t5-11b on CPU (to save GPU memory) can not solve the problem, I'm not sure how to solve it currently.

**Comment by victorup** [comment]
Thanks for your reply. I will try to use t5-11b again. 

By the way, what is the difference between small_baseline.zip, small_sft_2.zip and small_sft.zip?

**Comment by drboog** [comment]
small_baseline is trained without shift term, the other two are two shifted diffusion checkpoints. All of them are trained on CC dataset.

**Comment by victorup** [comment]
> 

I ran t5-11b model on CPU and the results were good. Thank you!

**Comment by victorup** [comment]
I also have a question about training. When running the following code:

```
if args.gradient_checkpointing:
        model.enable_gradient_checkpointing()
```

I received the following error message: `'ClipPrior' object has no attribute 'enable_gradient_checkpointing'`

**Comment by drboog** [comment]
> I also have a question about training. When running the following code:
> 
> ```
> if args.gradient_checkpointing:
>         model.enable_gradient_checkpointing()
> ```
> 
> I received the following error message: `'ClipPrior' object has no attribute 'enable_gradient_checkpointing'`

Oh, thanks for the information. 
Our original implementation was based on some company internal libraries, so I re-write the code before put it on Github. 
But I forgot about the gradient_checkpointing thing. I will delete gradient_checkpointing temporarily. I think the training should work without gradient_checkpointing.

**Comment by victorup** [comment]
Hi, how much GPU memory is required for training? I used 3090 GPUs with 24 GB memory, but it ran out of memory.

**Comment by rutuja1409** [comment]
> I also have a question about training. When running the following code:
> 
> ```
> if args.gradient_checkpointing:
>         model.enable_gradient_checkpointing()
> ```
> 
> I received the following error message: `'ClipPrior' object has no attribute 'enable_gradient_checkpointing'`

Hi @victorup I was trying to train the model with my dataset and was confused what to provide as a file for gaussian std and mean? Did you find a way to calculate std and mean of dataset? Also what is the path to t5 model?
Thank you for the help !!
